image: crhym3/go1.4-node0.10
git:
  depth: 1
script:
  - npm -q install
  - cd app && ../node_modules/bower/bin/bower install -q --allow-root && cd ..
  - gulp godeps
  # ensure the build works
  - gulp
  # backend testing
  - gulp backend:test
  # deploy to appspot if this is master branch
  - util/auto-deploy

